<?php
require_once __DIR__ . '/../auth.php';
require_once __DIR__ . '/../Logger.php';

requireLogin();

if ($_SESSION['role'] !== 'superadmin') {
    http_response_code(403);
    exit('Acesso negado.');
}

$action = $_GET['action'] ?? '';
$logger = new Logger($pdo);

if ($action === 'db_dump') {
    generateDbBackup($pdo, $logger);
} elseif ($action === 'full_backup') {
    generateFullBackup($pdo, $logger);
} else {
    http_response_code(400);
    echo "Ação inválida.";
}

function getDbDump($pdo) {
    $tables = [];
    $stmt = $pdo->query("SHOW TABLES");
    while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
        $tables[] = $row[0];
    }

    $sql = "-- SysReport Database Backup\n";
    $sql .= "-- Generated by Super Admin: " . ($_SESSION['username'] ?? 'Unknown') . "\n";
    $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
    $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $table) {
        $row2 = $pdo->query("SHOW CREATE TABLE $table")->fetch(PDO::FETCH_NUM);
        $sql .= "\n\n" . $row2[1] . ";\n\n";

        $rows = $pdo->query("SELECT * FROM $table");
        while ($row = $rows->fetch(PDO::FETCH_ASSOC)) {
            $sql .= "INSERT INTO $table VALUES(";
            $values = [];
            foreach ($row as $value) {
                if (is_null($value)) {
                    $values[] = "NULL";
                } else {
                    $values[] = "'" . addslashes($value) . "'";
                }
            }
            $sql .= implode(',', $values);
            $sql .= ");\n";
        }
    }

    $sql .= "\nSET FOREIGN_KEY_CHECKS=1;\n";
    return $sql;
}

function generateDbBackup($pdo, $logger) {
    $sql = getDbDump($pdo);
    $filename = 'backup_db_' . date('Y-m-d_H-i-s') . '.sql';

    $logger->log($_SESSION['user_id'], 'BACKUP_DB', 'Gerou backup do banco de dados: ' . $filename);

    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    echo $sql;
    exit;
}

function generateFullBackup($pdo, $logger) {
    if (!class_exists('ZipArchive')) {
        die('ZipArchive extension not loaded.');
    }

    $zip = new ZipArchive();
    $filename = 'backup_full_' . date('Y-m-d_H-i-s') . '.zip';
    $tmpFile = sys_get_temp_dir() . DIRECTORY_SEPARATOR . $filename;

    if ($zip->open($tmpFile, ZipArchive::CREATE) !== TRUE) {
        die("Cannot open <$tmpFile>\n");
    }

    // Add Project Files (recursively)
    // Assuming we are in src/api, go up to project root
    $rootPath = realpath(__DIR__ . '/../../');

    $files = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($rootPath),
        RecursiveIteratorIterator::LEAVES_ONLY
    );

    foreach ($files as $name => $file) {
        // Skip directories (they would be added automatically)
        if (!$file->isDir()) {
            // Get real and relative path for current file
            $filePath = $file->getRealPath();
            
            // Calculate relative path correctly for both Windows and Linux
            $relativePath = substr($filePath, strlen($rootPath) + 1);
            
            // Normalize slashes for ZIP (always use forward slashes)
            $relativePath = str_replace('\\', '/', $relativePath);

            // Skip the backup zip itself if it's being created inside (unlikely but safe)
            if (strpos($filePath, $filename) !== false) continue;
            
            // Skip .git, node_modules, vendor if needed (optional)
            if (strpos($relativePath, '.git') === 0) continue;

            $zip->addFile($filePath, $relativePath);
        }
    }

    // Add DB Dump inside Zip
    $sql = getDbDump($pdo);
    $zip->addFromString('database_dump.sql', $sql);

    $zip->close();

    $logger->log($_SESSION['user_id'], 'BACKUP_FULL', 'Gerou backup completo: ' . $filename);

    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . filesize($tmpFile));
    readfile($tmpFile);
    unlink($tmpFile);
    exit;
}
?>
